export const RECEIVE_CLIENTS='RECEIVE_CLIENTS';
export const UPDATE_CLIENT='UPDATE_CLIENT';
export const RECEIVE_MAPPING='RECEIVE_MAPPING';
export const INSERT_MAPPING='INSERT_MAPPING';
export const ADD_TO_SELECTION='ADD_TO_SELECTION';
export const REMOVE_FROM_SELECTION='REMOVE_FROM_SELECTION';
export const SWAP_SELECTION_AND_TARGET='USE_SELECTION_AS_TARGET';
export const SET_TARGET='SET_TARGET';
