export const UPDATE_SEARCH_FILTER='UPDATE_SEARCH_FILTER';
export const UPDATE_GLOBAL_SEARCH_FILTER='UPDATE_GLOBAL_SEARCH_FILTER';
export const UPDATE_SEARCH_RESULTS='UPDATE_SEARCH_RESULTS';
export const UPDATE_SEARCH_INDEX='UPDATE_SEARCH_INDEX';